### PR TITLE
add stagger sensor

### PR DESCRIPTION
**Pull request by Spells24**
add a new sensor for us to delay task execution

Having trouble running the unit test locally. I'm not sure if we even need or want the test though..

### CODE REVIEW

**Comment by Spells24** [comment]
Do we even run the unit tests? Doesn't look like we do

**Comment by dangermike** [comment]
code seems fine, but why are we doing this?

**Comment by Spells24** [comment]
I just figured if all partners kick off at the same time, they're all immediately going to run a BQ query, so might be worth just staggering their start times a bit. Not super necessary probably.. whatchu think?

**Comment by dangermike** [comment]
we have been limiting this by using Airflow pools

**Pull request closed without merging**
